version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - pip install awscli

  pre_build:
    commands:
      - echo "Running tests..."
      - cd djangoweb
      - python manage.py test --noinput
      - python manage.py check --deploy
      - cd ..

  build:
    commands:
      - echo "Building Django app..."
      - cd djangoweb
      - python manage.py collectstatic --noinput
      - cd ..
      - echo "Creating deployment package..."
      - tar -czf deploy.tar.gz djangoweb/ nginx/ scripts/ requirements.txt

  post_build:
    commands:
      - echo "Deploying to EC2 via SSH..."
      - |
        # Setup SSH for EC2 connection
        mkdir -p ~/.ssh
        echo "$EC2_SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        
        # Copy files to EC2
        scp -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key deploy.tar.gz $EC2_USER@$EC2_HOST:/home/$EC2_USER/
        
        # Run deployment commands on EC2
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key $EC2_USER@$EC2_HOST << 'EOF'
          cd /home/$EC2_USER/
          tar -xzf deploy.tar.gz
          cd djangoweb
          
          # Setup Python environment
          python3 -m venv venv
          source venv/bin/activate
          pip install -r ../requirements.txt
          
          # Run migrations
          python manage.py migrate
          
          # Setup nginx
          sudo cp ../nginx/django-app.conf /etc/nginx/sites-available/
          sudo ln -sf /etc/nginx/sites-available/django-app.conf /etc/nginx/sites-enabled/
          sudo nginx -t
          
          # Restart services
          sudo systemctl restart nginx
          sudo systemctl restart gunicorn
        EOF

artifacts:
  files:
    - '**/*'
  base-directory: '.'