version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Setting up SSH..."
      - mkdir -p ~/.ssh

  build:
    commands:
      - echo "Creating SSH key..."
      - |
        cat > ~/.ssh/key.pem << 'SSHKEY'
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
        NhAAAAAwEAAQAAAQEAn/ruIxqEb9s4GJ7GGp3aTmdiVHvRzFwXvcy8+BGCMtiGe5GnjLQm
        zyqiLPrFku9VR02fpJK8tq9NpyC1zcal9RjuFVyZMCmxskmwmcAbT/w7MPd6VCxLh8iGnj
        Tb4BDDaZpiv+LdJuNNlExzEZVzv12o9pWFnK3LqvVT03BoXecwMPzWldWSSZ2eTP+Z87bH
        Om8qKvT2ougO1lf4Tb3tBv2Cg62v4a/LdruOJWbY0aVzFxz5b45BYyr9RK9/xlIZFMyZHV
        X5DD6qra9MH41JWqc6zuDNlkcZ3skLtVfZmHE3GAhwNc16g1LSQclqLm8RmiTkSGnX/Y0t
        PAPzLwIEOQAAA+A4LuzoOC7s6AAAAAdzc2gtcnNhAAABAQCf+u4jGoRv2zgYnsYandpOZ2
        JUe9HMXBe9zLz4EYIy2IZ7kaeMtCbPKqIs+sWS71VHTZ+kkry2r02nILXNxqX1GO4VXJkw
        KbGySbCZwBtP/Dsw93pULEuHyIaeNNvgEMNpmmK/4t0m402UTHMRlXO/Xaj2lYWcrcuq9V
        PTcGhd5zAw/NaV1ZJJnZ5M/5nztsc6byoq9Pai6A7WV/hNve0G/YKDra/hr8t2u44lZtjR
        pXMXHPlvjkFjKv1Er3/GUhkUzJkdVfkMPqqtr0wfjUlapzrO4M2WRxneyQu1V9mYcTcYCH
        A1zXqDUtJByWoubxGaJORIadf9jS08A/MvAgQ5AAAAAwEAAQAAAQAAj7riOKeaVOSfgX8k
        fMVVXRuFPGICG5ihu+Q14qnYT9Y4/MvfvIoeVAH5sm+bEmf0NhuHUlSDN55IJd89d6MBdz
        LutEJ9XsgW3hdWkswFvdbfVx8AyJ8DPPrr9zeGU8i7yCTsk3k/N7EAAjytJR8g3s1HAENV
        x25djTrcFRroqXOe9GNP3TCTj0EanoveAXN10W9Q/QeJGzoEnZruK2BEXqkHnVMgNd8cji
        GPxDC2XmQZVB7msOpFRPwGdnRIjfWyT32+U2jbDqTWikgjTyhdZEazFiXrg89yQr9gapk+
        3D7U7aWoIlOIRLfaGcRGCGqSwVQYZZ0c1SW/nNGRDus5AAAAgH6YWwbBjs9qUOLVJWOklz
        O4WQePYn/m9zgOTNip9kKnrUd8pmNJBbQM+8wDROwAUpti+y06uRVygDCAvQm12wBqaevz
        IPr3DxBNAJcncA4O0IJCWyzhDVca1DWVhJCVZhLH1lzDJhwQjHlBcpaToIGCUAL+wbvkWE
        fKEIqWJjpEAAAAgQDb3zqjY6svyFo7beaejPsldLdoJsTqf7MrVriJTFbBq5sPvXf7YfI9
        PkEIr7Q+4HEozdsE4I2zOZ65gdTca5ggq8Lk9zP71Qs9pFxseInw949FvXFQMxUhkfhTC4
        ygoRJ3Ac3jiYp1kSe/akmMPgRrATuTuj3/ttAGnxmW8i0ZtwAAAIEAukRkaFdzWv4czd1C
        vHTZKmCMMxNiqgnfC75fYeZZU7wvOJcRQ3xnfim9LIfIVE+yqBgKDCRawSgmplMEGnC3dv
        8XAAoi5m9o9/ZEwysi35EgwpPUxP9SSpYPdJXJX2l3lHwYgck4Qp1MVLaIWtK1qb7dPNOA
        +2WdVr2s8YXAkY8AAAAlZWMyLXVzZXJAaXAtMTcyLTMxLTY0LTQ3LmVjMi5pbnRlcm5hbA
        ECAwQFBg==
        -----END OPENSSH PRIVATE KEY-----
        SSHKEY

      - chmod 600 ~/.ssh/key.pem
      - ssh-keyscan -H 3.239.115.151 >> ~/.ssh/known_hosts 2>/dev/null

      - echo "Testing SSH connection..."
      - ssh -o StrictHostKeyChecking=no -i ~/.ssh/key.pem ec2-user@3.239.115.151 "echo 'SSH OK'"

      - echo "Uploading project files..."
      - scp -o StrictHostKeyChecking=no -i ~/.ssh/key.pem -r djangoweb/* ec2-user@3.239.115.151:/home/ec2-user/djangoweb/

      - echo "Running migrations on EC2..."
      - |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/key.pem ec2-user@3.239.115.151 "
          cd /home/ec2-user/djangoweb &&
          source venv/bin/activate &&
          python manage.py migrate --noinput &&
          python manage.py collectstatic --noinput &&
          sudo systemctl restart gunicorn &&
          sudo systemctl restart nginx &&
          echo 'Deploy complete!'
        "

artifacts:
  files:
    - "**/*"
