# Generated by Django 3.2.12 on 2025-09-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('physical', 'Physical'), ('virtual', 'Virtual')], default='physical', max_length=10),
        ),
    ]
