# Generated by Django 3.2.12 on 2025-09-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menus',
            field=models.TextField(blank=True, null=True),
        ),
    ]
