name: build-and-deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - staging

env:
  TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r req.txt

      - name: Run migrations and collect static files (optional)
        run: |
          python manage.py migrate
          python manage.py collectstatic --no-input

  deploy_staging:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.base.ref == 'staging'

    steps:
      - name: Debugging Info
        run: |
          echo "EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}"
          echo "EC2_HOST: ${{ secrets.EC2_HOST }}"
          echo "EC2_USERNAME: ${{ secrets.EC2_USERNAME }}"
          echo "Current Directory: $(pwd)"

      - name: Deploy to Staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/django-web/djangoweb
            git pull origin staging
            source myenv/bin/activate
            pip install -r req.txt
            python manage.py migrate
            python manage.py runserver 0.0.0.0:8000 &

  deploy_main:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.base.ref == 'main'
    steps: []
