name: build-and-deploy

on:
  push:
    branches:
      - main
      - staging

env:
  TARGET_BRANCH: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r req.txt

      - name: Run migrations and collect static files
        run: |
          python manage.py migrate
          python manage.py collectstatic --no-input

  deploy_staging:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/staging'

    steps:
      - name: Deploy to Staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/django-web/djangoweb
            git pull origin staging
            source myenv/bin/activate
            pip install -r req.txt
            python manage.py migrate
            nohup python manage.py runserver 0.0.0.0:8000 &

  deploy_prod:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/django-web/djangoweb
            git pull origin main
            source myenv/bin/activate
            pip install -r req.txt
            python manage.py migrate
            nohup python manage.py runserver 0.0.0.0:8000 &
