name: build-and-deploy

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "No requirements.txt found"; fi

      - name: Run migrations
        run: |
          if [ -f manage.py ]; then python manage.py migrate; else echo "No manage.py found"; fi

      - name: Collect static files
        run: |
          if [ -f manage.py ]; then python manage.py collectstatic --no-input; else echo "No static files to collect"; fi

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/django-web/djangoweb || exit 1
            git pull origin ${{ github.ref_name }}
            source myenv/bin/activate || python3 -m venv myenv && source myenv/bin/activate
            pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            python manage.py migrate
            nohup python manage.py runserver 0.0.0.0:8000 > server.log 2>&1 &
